name: Sync OpenFootManager Develop Branch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Remove old directory
        run: rm -rf openfootmanager

      - name: Clone into openfootmanager directory
        run: |
          git clone --depth 1 --branch develop https://github.com/openfootmanager/openfootmanager.git openfootmanager

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add openfootmanager
          git commit -m "Update openfootmanager (develop branch)" || echo "No changes"
          git push
